### ISSUE TITLE
I just wanted to cross the lake..

### ISSUE THREAD

**Issue by theFuzzyWarble** [Markil3/MinecraftImmersiveHUD#1]
```
MC 1.16.5 -> [fabric-loader-0.11.3-1.16.5]
Immersive HUD 1.0-1.16.4-fabric

```
All I did was craft a boat, throw it in the water and jumped on...
all I got for it was this [crash report](https://pastebin.com/g53j68yz)

Any ideas?

**Comment by Markil3** [comment]
Hot take: I'm guessing that my mod is taking the EntityBoat and trying to treat it like a LivingEntity. This works fine for horses and such, but since boats and minecarts aren't alive, it doesn't work. I probably forgot to account for this.
Unless there is something deeper going on, it sounds pretty simple. I'll see if I can get a fix done by next Tuesday. Thanks for letting me know!

**Comment by theFuzzyWarble** [comment]
Not a problem. Will disable for now and check back!
Thanks for checking it out.

**Comment by Markil3** [comment]
Right, that should fix it. I want to investigate another bug/crash before I make another set of releases. However, you are free to build it yourself and use that.

**Comment by theFuzzyWarble** [comment]
> Right, that should fix it. I want to investigate another bug/crash before I make another set of releases. However, you are free to build it yourself and use that.

BINGO!#@ That did the trick. Swapped in the new "1.0.1" patch ;) and loaded right up.
"I'm On A MF'n Boat!@"

Thanks @Markil3 !

--UPDATE--
Disregard, it loaded. I am on boat. But when I right click the boat, I get a 'Saving' screen then the same crash. :(

--UPDATE #2--
As this is my first attempt at builing an MC mod I don't think I did it right.
It didn't compile the classes.

I'll try again tomorrow and follow up.

**Comment by Markil3** [comment]
Based on your crash report, you should be on Linux. All you really need to do is cd into the directory where the mod was downloaded and run the "./gradlew build" command. Since you probably haven't used Gradle before, it will download Gradle, then all the libraries Minecraft needs, and then it will decompile Minecraft before it finally gets to building it. The whole process can take 10 to 15 minutes overall, depending on your computer and internet speeds. In the end, the files will be in MinecraftImmersiveHud/build/libs folder.

**Comment by theFuzzyWarble** [comment]
> Based on your crash report, you should be on Linux...
..In the end, the files will be in MinecraftImmersiveHud/build/libs folder.

Yup! ok, yeah i was grabbing the wrong files then hehe.
Just tested and it works!! Thanks again
